package Airline;

/**
* Airline/AdminServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AdminService.idl
* lundi 8 janvier 2024 17 h 31 GMT+01:00
*/

public final class AdminServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public Airline.AdminService value = null;

  public AdminServiceHolder ()
  {
  }

  public AdminServiceHolder (Airline.AdminService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Airline.AdminServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Airline.AdminServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Airline.AdminServiceHelper.type ();
  }

}
