package Airline;


/**
* Airline/AdminServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AdminService.idl
* lundi 8 janvier 2024 17 h 31 GMT+01:00
*/

public interface AdminServiceOperations 
{
  void addNewFlight (String code, String departureAirport, String arrivalAirport, String departureTime, String arrivalTime, double price);
  void addNewAirport (String code, String city);
  void registerNewPassenger (String passengerName, String phonenumber, String address, String email, String passport, String seattype);
  void viewAllFlights ();
  void editFlight ();
  void editAirport ();
} // interface AdminServiceOperations
