package Airline;

/**
* Airline/AuthServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AuthService.idl
* lundi 8 janvier 2024 17 h 30 GMT+01:00
*/

public final class AuthServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public Airline.AuthService value = null;

  public AuthServiceHolder ()
  {
  }

  public AuthServiceHolder (Airline.AuthService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Airline.AuthServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Airline.AuthServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Airline.AuthServiceHelper.type ();
  }

}
