package Airline;


/**
* Airline/AuthService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AuthService.idl
* lundi 8 janvier 2024 17 h 30 GMT+01:00
*/

public interface AuthService extends AuthServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface AuthService
