package Airline;

/**
* Airline/ClientServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ClientService.idl
* lundi 8 janvier 2024 17 h 31 GMT+01:00
*/

public final class ClientServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public Airline.ClientService value = null;

  public ClientServiceHolder ()
  {
  }

  public ClientServiceHolder (Airline.ClientService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Airline.ClientServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Airline.ClientServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Airline.ClientServiceHelper.type ();
  }

}
