package Airline;


/**
* Airline/_AdminServiceStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AdminService.idl
* lundi 8 janvier 2024 17 h 31 GMT+01:00
*/

public class _AdminServiceStub extends org.omg.CORBA.portable.ObjectImpl implements Airline.AdminService
{

  public void addNewFlight (String code, String departureAirport, String arrivalAirport, String departureTime, String arrivalTime, double price)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("addNewFlight", true);
                $out.write_string (code);
                $out.write_string (departureAirport);
                $out.write_string (arrivalAirport);
                $out.write_string (departureTime);
                $out.write_string (arrivalTime);
                $out.write_double (price);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                addNewFlight (code, departureAirport, arrivalAirport, departureTime, arrivalTime, price        );
            } finally {
                _releaseReply ($in);
            }
  } // addNewFlight

  public void addNewAirport (String code, String city)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("addNewAirport", true);
                $out.write_string (code);
                $out.write_string (city);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                addNewAirport (code, city        );
            } finally {
                _releaseReply ($in);
            }
  } // addNewAirport

  public void registerNewPassenger (String passengerName, String phonenumber, String address, String email, String passport, String seattype)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("registerNewPassenger", true);
                $out.write_string (passengerName);
                $out.write_string (phonenumber);
                $out.write_string (address);
                $out.write_string (email);
                $out.write_string (passport);
                $out.write_string (seattype);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                registerNewPassenger (passengerName, phonenumber, address, email, passport, seattype        );
            } finally {
                _releaseReply ($in);
            }
  } // registerNewPassenger

  public void viewAllFlights ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("viewAllFlights", true);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                viewAllFlights (        );
            } finally {
                _releaseReply ($in);
            }
  } // viewAllFlights

  public void editFlight ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("editFlight", true);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                editFlight (        );
            } finally {
                _releaseReply ($in);
            }
  } // editFlight

  public void editAirport ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("editAirport", true);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                editAirport (        );
            } finally {
                _releaseReply ($in);
            }
  } // editAirport

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Airline/AdminService:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _AdminServiceStub
