package Airline;


/**
* Airline/ClientServicePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ClientService.idl
* lundi 8 janvier 2024 17 h 31 GMT+01:00
*/

public abstract class ClientServicePOA extends org.omg.PortableServer.Servant
 implements Airline.ClientServiceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("registerNewPassenger", new java.lang.Integer (0));
    _methods.put ("viewAllFlights", new java.lang.Integer (1));
    _methods.put ("availableseats", new java.lang.Integer (2));
    _methods.put ("payment", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Airline/ClientService/registerNewPassenger
       {
         String passengerName = in.read_string ();
         String phonenumber = in.read_string ();
         String address = in.read_string ();
         String email = in.read_string ();
         String passport = in.read_string ();
         String seattype = in.read_string ();
         this.registerNewPassenger (passengerName, phonenumber, address, email, passport, seattype);
         out = $rh.createReply();
         break;
       }

       case 1:  // Airline/ClientService/viewAllFlights
       {
         this.viewAllFlights ();
         out = $rh.createReply();
         break;
       }

       case 2:  // Airline/ClientService/availableseats
       {
         this.availableseats ();
         out = $rh.createReply();
         break;
       }

       case 3:  // Airline/ClientService/payment
       {
         double pay = in.read_double ();
         this.payment (pay);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Airline/ClientService:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ClientService _this() 
  {
    return ClientServiceHelper.narrow(
    super._this_object());
  }

  public ClientService _this(org.omg.CORBA.ORB orb) 
  {
    return ClientServiceHelper.narrow(
    super._this_object(orb));
  }


} // class ClientServicePOA
