package Airline;


/**
* Airline/Flight.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ClientService.idl
* lundi 8 janvier 2024 17 h 31 GMT+01:00
*/

public final class Flight implements org.omg.CORBA.portable.IDLEntity
{
  public String code = null;
  public String departureAirport = null;
  public String arrivalAirport = null;
  public String departureTime = null;
  public String arrivalTime = null;
  public double price = (double)0;

  public Flight ()
  {
  } // ctor

  public Flight (String _code, String _departureAirport, String _arrivalAirport, String _departureTime, String _arrivalTime, double _price)
  {
    code = _code;
    departureAirport = _departureAirport;
    arrivalAirport = _arrivalAirport;
    departureTime = _departureTime;
    arrivalTime = _arrivalTime;
    price = _price;
  } // ctor

} // class Flight
