package Airline;


/**
* Airline/FlightListHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ClientService.idl
* lundi 8 janvier 2024 17 h 31 GMT+01:00
*/

abstract public class FlightListHelper
{
  private static String  _id = "IDL:Airline/FlightList:1.0";

  public static void insert (org.omg.CORBA.Any a, Airline.Flight[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Airline.Flight[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = Airline.FlightHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (Airline.FlightListHelper.id (), "FlightList", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Airline.Flight[] read (org.omg.CORBA.portable.InputStream istream)
  {
    Airline.Flight value[] = null;
    int _len0 = istream.read_long ();
    value = new Airline.Flight[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = Airline.FlightHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Airline.Flight[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      Airline.FlightHelper.write (ostream, value[_i0]);
  }

}
