package Airline;


/**
* Airline/FlightHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ClientService.idl
* lundi 8 janvier 2024 17 h 31 GMT+01:00
*/

abstract public class FlightHelper
{
  private static String  _id = "IDL:Airline/Flight:1.0";

  public static void insert (org.omg.CORBA.Any a, Airline.Flight that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Airline.Flight extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [6];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "code",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "departureAirport",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "arrivalAirport",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[3] = new org.omg.CORBA.StructMember (
            "departureTime",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[4] = new org.omg.CORBA.StructMember (
            "arrivalTime",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_double);
          _members0[5] = new org.omg.CORBA.StructMember (
            "price",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (Airline.FlightHelper.id (), "Flight", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Airline.Flight read (org.omg.CORBA.portable.InputStream istream)
  {
    Airline.Flight value = new Airline.Flight ();
    value.code = istream.read_string ();
    value.departureAirport = istream.read_string ();
    value.arrivalAirport = istream.read_string ();
    value.departureTime = istream.read_string ();
    value.arrivalTime = istream.read_string ();
    value.price = istream.read_double ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Airline.Flight value)
  {
    ostream.write_string (value.code);
    ostream.write_string (value.departureAirport);
    ostream.write_string (value.arrivalAirport);
    ostream.write_string (value.departureTime);
    ostream.write_string (value.arrivalTime);
    ostream.write_double (value.price);
  }

}
